import streamlit as st
import pandas as pd

st.set_page_config(
    page_title="UA Majors",
    layout='wide'
)

st.page_link("Home.py", label="Home", icon="🏠")

st.title("University of Alabama Majors for Your Prediction")
st.write("These are the University of Alabama majors that are contained in your predicted major category.")
st.write("Click on the link to view information about the major, the classes needed at The University of Alabama, and career opportunities.")
st.write("""The number next to each major is its average salary per year. These figures are estimates and this is **not** starting salary information. Many majors lead to jobs that require Master's degrees or other graduate schooling, 
         but these salaries typically do not account for careers that require graduate schooling and are salaries for jobs obtained with just the undergraduate degree listed. Some majors do not have salary data, as they are not specific 
         enough or the career options are too broad. Some majors have salary data with job titles in parentheses that this data corresponds to, though there are other jobs with other salaries available for those pursuing that degree. 
         All salary data has been taken from <a href="https://www.mynextmove.org">My Next Move</a> unless otherwise noted with an "*".""", unsafe_allow_html=True)
if st.button("More about your HEXACO scores!"):
    st.switch_page('pages/3_HexacoResults.py')
st.write('')
st.write("Your prediction: ", st.session_state.prediction)

if st.session_state.prediction == "Health Sciences":
    st.subheader('Health Sciences:')
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/human-environmental-sciences/human-development/addiction-recovery-bs/">Addiction and Recovery</a>, BS - $49,710""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/human-environmental-sciences/human-nutrition-hospitality-management/food-nutrition-bs/">Food and Nutrition</a>, BS - $79,680""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/education/kinesiology/bs/">Kinesiology</a>, BS - $51,350""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/nursing/rn-bsn/">Nursing</a>, RN to BSN - $121,610""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/nursing/bsn/">Nursing</a>, BSN - $121,610""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/human-environmental-sciences/health-science/public-health-bs/">Public Health</a>, BS - $77,552* (Health Care Administration)""", unsafe_allow_html=True)
    st.write('')
    st.markdown("""*: Salary data taken from <a href="https://www.wsj.com/public/resources/documents/info-Degrees_that_Pay_you_Back-sort.html">The Wall Street Journal</a> (2017). Salaries taken from the 
            "Mid-Career Median Salary" column and then adjusted for inflation to reflect a salary in 2024.""", unsafe_allow_html=True)
elif st.session_state.prediction == "Biological Sciences":
    st.subheader('Biological Sciences:')
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/biological-sciences/biology-bs/">Biology</a>, BS - $87,300""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/biological-sciences/microbiology-bs/">Microbiology</a>, BS - $81,990""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/psychology/neuroscience-bs/">Neuroscience</a>, BS - $57,380 (Laboratory Technician)""", unsafe_allow_html=True)
    st.write('')
elif st.session_state.prediction == "Engineering":
    st.subheader('Engineering:')
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/engineering/aerospace-mechanics/bs/">Aerospace Engineering</a>, BS - $126,880""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/engineering/civil-construction-environmental/architectural-engineering-bs/">Architectural Engineering</a>, BS - $159,920""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/engineering/chemical-biological/bsche/">Chemical Engineering</a>, BSChE - $106,260""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/engineering/civil-construction-environmental/civil-engineering-bs/">Civil Engineering</a>, BS - $89,940""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/engineering/electrical-computer/computer-engineering-bs/">Computer Engineering</a>, BS - $132,360""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/engineering/computer-science/bs/">Computer Science</a>, BS - $136,620""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/engineering/civil-construction-environmental/construction-engineering-bs/">Construction Engineering</a>, BS - $101,480""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/engineering/computer-science/cyber-security-bs/">Cyber Security</a>, BS - $98,720""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/engineering/electrical-computer/bsee/">Electrical Engineering</a>, BS - $103,320""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/engineering/civil-construction-environmental/environmental-engineering-bs/">Environmental Engineering</a>, BS - $96,530""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/engineering/mechanical/manufacturing-systems-engineering-bs/">Manufacturing Systems Engineering</a>, BS - $96,350""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/engineering/mechanical/bsme/">Mechanical Engineering</a>, BS - $96,310""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/engineering/metallurgical-materials/bs/">Metallurgical Engineering</a>, BS - $100,140""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/engineering/electrical-computer/musical-audio-engineering-bs/">Musical Audio Engineering</a>, BS - $60,670""", unsafe_allow_html=True)
    st.write('')
elif st.session_state.prediction == "Physical Sciences / Mathematics":
    st.subheader('Physical Sciences / Mathematics:')
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/chemistry/bch/">Chemistry</a>, BCH - $80,670""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/chemistry/bs/">Chemistry</a>, BS - $80,670""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/environmental-science/bs/">Environmental Science</a>, BS - $76,480""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/geography-and-the-environment/geography-ba/">Geography</a>, BA - $88,900""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/geography-and-the-environment/geography-bs/">Geography</a>, BS - $88,900""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/geology/ba/">Geology</a>, BA - $87,480""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/geology/bs/">Geology</a>, BS - $87,480""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/geology/bsg/">Geology</a>, BSG - $87,480""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/biological-sciences/marine-science-bs/">Marine Science</a>, BS - $96,910""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/mathematics/bs/">Mathematics</a>, BS - $112,110""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/physics-astronomy/bs/">Physics</a>, BS - $142,850""", unsafe_allow_html=True)
    st.write('')
elif st.session_state.prediction == "Business":
    st.subheader('Business:')
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/commerce-business-administration/accountancy/bs/">Accounting</a>, BS - $78,000""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/communication-information-sciences/advertising-public-relations/advertising-ba/">Advertising</a>, BA - $58,450""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/commerce-business-administration/information-systems-statistics-management-science/business-cyber-security-bs/">Business Cyber Security</a>, BS - $112,000""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/political-science/economics-ba/">Economics</a>, BA - $113,940""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/commerce-business-administration/economics-finance-legal-studies/economics-bs/">Economics</a>, BS - $113, 940""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/commerce-business-administration/economics-finance-legal-studies/finance-bs/">Finance</a>, BS - $95,080""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/commerce-business-administration/management/general-business-bs/">General Business</a>, BS - $92,269* (Business Management)""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/commerce-business-administration/information-systems-statistics-management-science/mis/">Management Information Systems</a>, BS - $95,290""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/commerce-business-administration/management/bs/">Management</a>, BS - $92,269*""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/commerce-business-administration/marketing/bs/">Marketing</a>, BS - $68,230""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/commerce-business-administration/information-systems-statistics-management-science/om-bs/">Operations Management</a>, BS - $98,100""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/human-environmental-sciences/human-nutrition-hospitality-management/sport-management-bs/">Sports Management</a>, BS - $82,530""", unsafe_allow_html=True)
    st.write('')
    st.markdown("""*: Salary data taken from <a href="https://www.wsj.com/public/resources/documents/info-Degrees_that_Pay_you_Back-sort.html">The Wall Street Journal</a> (2017). Salaries taken from the 
            "Mid-Career Median Salary" column and then adjusted for inflation to reflect a salary in 2024.""", unsafe_allow_html=True)
elif st.session_state.prediction == "Social Sciences":
    st.subheader('Social Sciences:')
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/communication-information-sciences/communication-studies/ba/">Communication Studies</a>, BAC - $89,581*""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/communicative-disorders/ba/">Communicative Disorders</a>, BA - $40,420""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/human-environmental-sciences/consumer-science/bs/">Consumer Sciences</a>, BS - $74,480* (Sociology)""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/communication-information-sciences/journalism-creative-media/creative-media-ba/">Creative Media</a>, BA - $87,662*""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/criminology-criminal-justice/ba/">Criminology & Criminal Justice</a>, BA - $72,049*""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/human-environmental-sciences/human-development/echs-major/">Early Childhood Education</a>, BS - $35,330""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/education/special-education/early-childhood-special-education/">Early Childhood Special Education</a> - $62,390""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/education/curriculum-instruction/elementary-bse/">Elementary Education</a>, BSE - $61,690""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/human-environmental-sciences/human-nutrition-hospitality-management/hospitality-management-bs/">Hospitality Management</a>, BS - $73,585*""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/human-environmental-sciences/human-development/hdfs-major/">Human Development and Family Studies</a>, BS - $74,480* (Sociology)""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/human-environmental-sciences/bs/">Human Environmental Sciences</a>, BS - $74,480* (Sociology)""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/education/music/instrumental-education-bse/">Music Education (Certification in Instrumental Music)</a>, BSE - $61,690 (Elementary School Teachers)""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/education/music/vocal-choral-education-bse/">Music Education (Certification in Vocal/Choral Music)</a>, BSE - $61,690 (Elementary School Teachers)""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/communication-information-sciences/journalism-creative-media/news-media-ba/">News Media</a>, BA - $55,960""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/political-science/ba/">Political Science</a>, BA - $128,020""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/psychology/bs/">Psychology</a>, BA - $77,296*""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/communication-information-sciences/advertising-public-relations/public-relations-ba/">Public Relations</a>, BA - $67,440""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/education/curriculum-instruction/secondary-teaching-learning-bse/">Secondary Education</a>, BSE - $62,360""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/social-work/bsw/">Social Work</a>, BSW""", unsafe_allow_html=True)
    st.write('')
    st.markdown("""*: Salary data taken from <a href="https://www.wsj.com/public/resources/documents/info-Degrees_that_Pay_you_Back-sort.html">The Wall Street Journal</a> (2017). Salaries taken from the 
            "Mid-Career Median Salary" column and then adjusted for inflation to reflect a salary in 2024.""", unsafe_allow_html=True)
elif st.session_state.prediction == "Visual and Performing Arts":
    st.subheader('Visual and Performing Arts:')
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/theatre-dance/dance-ba/">Dance</a>, BA - $50,990""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/music/composition-bm/">Music Composition</a>, BM - $62,940""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/music/performance-bm/">Music Performance</a>, BM""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/music/theory-bm/">Music Theory</a>, BM""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/music/therapy-bm/">Music Therapy</a>, BM - $60,800""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/music/ba/">Music</a>, BA - $70,385*""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/music/music-arts-administration-concentration-ba/">Music with a Concentration in Arts and Administration</a>, BA - 70,385*""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/art-art-history/studio-art-ba/">Studio Art</a>, BFA - $60,380 (Curator)""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/theatre-dance/theatre-ba/">Theatre</a>, BA - $72,817* (Drama)""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/theatre-dance/theatre-bfa/">Theatre</a>, BFA - $72,817* (Drama)""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/theatre-dance/theatre-musical-track-ba/">Theatre with Musical Theatre Concentration</a>, BA - $72,817* (Drama)""", unsafe_allow_html=True)
    st.write('')
    st.markdown("""*: Salary data taken from <a href="https://www.wsj.com/public/resources/documents/info-Degrees_that_Pay_you_Back-sort.html">The Wall Street Journal</a> (2017). Salaries taken from the 
            "Mid-Career Median Salary" column and then adjusted for inflation to reflect a salary in 2024.""", unsafe_allow_html=True)
elif st.session_state.prediction == "Humanities":
    st.subheader('Humanities:')
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/gender-race-studies/ba/">African American Studies</a>, BA - $74,480* (Sociology)""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/american-studies/ba/">American Studies</a>, BA - $74,480* (Sociology)""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/anthropology/ba/">Anthropology</a>, BA - $63,940""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/human-environmental-sciences/clothing-textiles-interior-design/apparel-textiles-bs/">Apparel and Textiles</a>, BS - $76,700""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/new-college/applied-liberal-arts-and-sciences-ba/">Applied Liberal Arts and Sciences</a>, BA""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/art-art-history/art-history-ba/">Art History</a>, BA - $83,055*""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/english/ba/">English</a>, BA - $82,799*""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/modern-languages-classics/foreign-languages-literature-ba/">Foreign Languages and Literature</a>, BA""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/art-art-history/graphic-design-bfa/">Graphic Design</a>, BFA - $57,990""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/history/ba/">History</a>, BA - $65,540""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/new-college/interdisciplinary-studies-ba/">Interdisciplinary Studies</a>, BA""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/new-college/interdisciplinary-studies-bs/">Interdisciplinary Studies</a>, BS""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/human-environmental-sciences/clothing-textiles-interior-design/interior-design-bs/">Interior Design</a>, BS - $61,590""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/political-science/international-studies-ba/">International Studies</a>, BA - $103,530*""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/philosophy/ba/">Philosophy</a>, BA - $103,914*""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/religious-studies/ba/">Religious Studies</a>, BA - $66,546*""", unsafe_allow_html=True)
    st.markdown("""<a href="https://catalog.ua.edu/undergraduate/arts-sciences/modern-languages-classics/spanish-ba/">Spanish</a>, BA - $67,954*""", unsafe_allow_html=True)
    st.write('')
    st.markdown("""*: Salary data taken from <a href="https://www.wsj.com/public/resources/documents/info-Degrees_that_Pay_you_Back-sort.html">The Wall Street Journal</a> (2017). Salaries taken from the 
            "Mid-Career Median Salary" column and then adjusted for inflation to reflect a salary in 2024.""", unsafe_allow_html=True)